# Generated by Django 5.2.3 on 2025-06-19 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=100)),
                ('phone', models.CharField(max_length=100)),
                ('sub', models.CharField(choices=[('General Inquiry', 'General Inquiry'), ('Order Information', 'Order Information'), ('Catering Services', 'Catering Services'), ('Feedback', 'Feedback'), ('Other', 'Other')], max_length=50)),
                ('msg', models.TextField()),
                ('date', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
